import LogoutButton from "@/components/LogoutButton";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/lib/providers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { PropsWithChildren } from "react";
import Sidebar from "@/components/Sidebar";
import "three-dots/dist/three-dots.css";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className="">
      <body className="flex items-start justify-between">
        <Providers>
          {user && <Sidebar user={user}/>}
          <main className={`grid w-full h-full ${user && `pl-[300px]`}`}>
            {user && <Header />}
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
